language: scala
scala:
- 2.11.0
- 2.12.0
jdk:
- oraclejdk8
script:
- sbt -J-Xmx4g ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport coverageAggregate
after_success:
- bash <(curl -s https://codecov.io/bash)
- sbt ++$TRAVIS_SCALA_VERSION unidoc
env:
  global:
    - CODECOV_TOKEN=d6c80769-94fc-4f7b-a682-a95b94f3d755
    secure: v2syKSa34C9qABysqXMmK5o1da8Aye0AoKH7Xj9jaTpHNwsVIpjYXB4ysdJ1AM5bXjNx4CwKTt5z086vehyaKEkqciRYrZJR3Au6EP4SxFmYynecWE/Hs/8BmsNMxqC90h9jspH8P8rvGGkUXKa7nDR3W5I73qzrW2DiRytblIspS/0K9VrkIM09GPSEclllkMUKSy1wl2Iyu7eYWcsMUnU34GHpt5Lx0DtIGZ3snefBtAN0Eszp2hx7Y9WpMjxq1V0WscQGFCJRjCvaR6Y8xHZ92MLcsPlXk1aLGDgiQ1LTw8Z1vh2yYP2sUVCVbfuZ5xYfQnyew9hDQN5LRnq7ch8a9v9Z5oHWhm+17S0go06xq3r93ibK1BsWuDSUpyfhdV0VdNgEPxDjfkmm5I7PCERHwClUBi1hGilFpboxglE/Nih9CZ4vost8w6MRtNE/h4tZrVQpdIKqffFtBgB4rgrE2LKJpuftcyWAEw2Rm35wy81vkt/p47nwNJ9a9V/cLaUN/+PkfWYjMyFoe6QrAjaiPd6ndcj6cuXS6hjLv7jCKIokkFs/bEMg3lUZkhFHLQBE33fctV6qWfzFyhpR4ArB3tHFOBLWbZfJqmoTx5MLoLS8Mw9aV4OQlynQVKNNdpD3dnabQBXEOcp2OniUErTPo7gf704BQTNMcgDq8Ls=
